javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\AUIN\AUINReceiver.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\AUIN\AUINSender.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\COAI\COAIReceiver.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\COAI\COAISender.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\CONF\ConfSender.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\CONF\ReceiverConf.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\main\Main.java
javac C:\Users\solen\Documents\IITM\Network Security\Lab 3\SourceFiles\main\GenerateKey.java